/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/ping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 健康检查 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example ok */
                            status?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ideas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取idea列表（带分页） */
        get: {
            parameters: {
                query?: {
                    /** @example 1 */
                    page?: number;
                    /** @example 10 */
                    pageSize?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功获取分页列表，可能为空 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PaginatedIdeas"];
                    };
                };
                400: components["responses"]["BadRequest"];
            };
        };
        put?: never;
        /** 创建新灵感 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateIdeaInput"];
                };
            };
            responses: {
                /** @description Successfully created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Idea"];
                    };
                };
                400: components["responses"]["BadRequest"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ideas/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 批量获取灵感 */
        get: {
            parameters: {
                query: {
                    /** @example 550e8400-e29b-41d4-a716-446655440000,550e8400-e29b-41d4-a716-446655440001 */
                    ids: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功获取批量灵感结果 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items: components["schemas"]["Idea"][];
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ideas/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取灵感详情 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @example 550e8400-e29b-41d4-a716-446655440000 */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Idea"];
                    };
                };
                400: components["responses"]["BadRequest"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        /** 删除灵感 */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content (Successfully deleted) */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["BadRequest"];
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        /** 部分更新灵感 */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateIdeaInput"];
                };
            };
            responses: {
                /** @description Updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Idea"];
                    };
                };
                400: components["responses"]["BadRequest"];
                404: components["responses"]["NotFound"];
            };
        };
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description 灵感状态
         * @enum {string}
         */
        IdeaStatus: "draft" | "published" | "archived";
        CreateIdeaInput: {
            title: components["schemas"]["IdeaTitle"];
            /** @default draft */
            status: components["schemas"]["IdeaStatus"];
        };
        /** @description 仅包含需要更新的字段 */
        UpdateIdeaInput: {
            title?: components["schemas"]["IdeaTitle"];
            status?: components["schemas"]["IdeaStatus"];
        };
        Idea: {
            /** Format: uuid */
            id: string;
            title: components["schemas"]["IdeaTitle"];
            status: components["schemas"]["IdeaStatus"];
            /**
             * Format: uuid
             * @description 服务端写入的资源归属用户 id，客户端不可在 request 中提交
             */
            ownerId: string;
            /**
             * Format: date-time
             * @description 服务端生成的创建时间
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description 服务端自动维护的最后更新时间
             */
            updatedAt: string;
        };
        /** @example 我的新项目 */
        IdeaTitle: string;
        /** @example 这是一个深刻的创意... */
        IdeaContent: string;
        PaginationMeta: {
            /** @example 100 */
            total: number;
            /** @example 1 */
            page: number;
            /** @example 10 */
            pageSize: number;
            /** @example 10 */
            totalPages: number;
            /** @example true */
            hasNextPage: boolean;
        };
        PaginatedIdeas: {
            items: components["schemas"]["Idea"][];
            meta: components["schemas"]["PaginationMeta"];
        };
        Error: {
            /**
             * @description 业务错误码
             * @example INVALID_PARAMS
             */
            code: string;
            /**
             * @description 提示信息
             * @example 标题不能为空
             */
            message: string;
            /**
             * @description 唯一请求ID
             * @example req-123456
             */
            requestId: string;
        };
    };
    responses: {
        /** @description 请求参数错误 */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 资源未找到 */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
